#!/usr/bin/env node

/**
 * DashClaw Interactive Setup
 *
 * One command to go from zero to running dashboard:
 *   node scripts/setup.mjs
 *
 * Handles: env config, dependency install, database migrations, build.
 * Cross-platform (Windows, Mac, Linux). Idempotent — safe to re-run.
 */

process.on('unhandledRejection', (reason) => {
  console.error('Unhandled Rejection:', reason);
  process.exit(1);
});

import fs from 'node:fs';
import crypto from 'node:crypto';
import { execFileSync, spawn } from 'node:child_process';
import readline from 'node:readline';

/* ── helpers ── */

const isWin = process.platform === 'win32';

function ask(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function banner(text) {
  const line = '='.repeat(48);
  console.log(`\n  ${line}\n   ${text}\n  ${line}\n`);
}

function step(n, total, msg) {
  console.log(`\n  [${n}/${total}] ${msg}\n`);
}

function ok(msg) { console.log(`  ✅ ${msg}`); }
function warn(msg) { console.log(`  ⚠️  ${msg}`); }
function fail(msg) { console.error(`  ❌ ${msg}`); }

function run(cmd, args, opts = {}) {
  try {
    execFileSync(cmd, args, { stdio: 'inherit', shell: true, ...opts });
    return true;
  } catch {
    return false;
  }
}

function parseEnvFile(text) {
  const env = {};
  for (const line of text.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const idx = t.indexOf('=');
    if (idx === -1) continue;
    env[t.slice(0, idx).trim()] = t.slice(idx + 1).trim();
  }
  return env;
}

function writeEnvFile(env) {
  const order = [
    'DASHCLAW_MODE', 'NEXT_PUBLIC_DASHCLAW_MODE',
    'DATABASE_URL', 'DASHCLAW_DB_DRIVER',
    'NEXTAUTH_URL', 'NEXTAUTH_SECRET',
    'DASHCLAW_API_KEY', 'ENCRYPTION_KEY', 'CRON_SECRET',
  ];
  const lines = [`# Generated by scripts/setup.mjs on ${new Date().toISOString()}`];
  for (const k of order) {
    if (env[k] != null) lines.push(`${k}=${env[k]}`);
  }
  const extras = Object.keys(env).filter(k => !order.includes(k)).sort();
  if (extras.length) {
    lines.push('', '# Additional settings');
    for (const k of extras) lines.push(`${k}=${env[k]}`);
  }
  fs.writeFileSync('.env.local', lines.join('\n') + '\n', 'utf8');
}

function b64url(n) {
  return crypto.randomBytes(n).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

function redactSecret(value, keep = 4) {
  if (!value) return '(unset)';
  const text = String(value);
  if (text.length <= keep) return '*'.repeat(text.length);
  return `${'*'.repeat(Math.max(8, text.length - keep))}${text.slice(-keep)}`;
}

/* ── main ── */

async function main() {
  banner('DashClaw Setup');

  const TOTAL = 6;
  const envPath = '.env.local';
  const hasEnv = fs.existsSync(envPath);
  let env = hasEnv ? parseEnvFile(fs.readFileSync(envPath, 'utf8')) : {};

  // ── Step 1: Database ──
  step(1, TOTAL, 'Database connection');

  // Allow DATABASE_URL override from environment (e.g. $env:DATABASE_URL="..." on PowerShell)
  if (process.env.DATABASE_URL && process.env.DATABASE_URL !== env.DATABASE_URL) {
    env.DATABASE_URL = process.env.DATABASE_URL;
    ok(`Using DATABASE_URL from environment (${env.DATABASE_URL.replace(/\/\/[^@]+@/, '//***@').replace(/\?.*/, '')})`);
  } else if (env.DATABASE_URL) {
    const masked = env.DATABASE_URL.replace(/\/\/[^@]+@/, '//***@').replace(/\?.*/, '');
    ok(`DATABASE_URL already set (${masked})`);
    const change = await ask('  Change it? [y/N]: ');
    if (change.toLowerCase() === 'y') {
      delete env.DATABASE_URL;
    }
  }

  if (!env.DATABASE_URL) {
    console.log('  You need a PostgreSQL database. Pick one:\n');
    console.log('  [1] Local Docker (fastest for dev)');
    console.log('      Requires Docker Desktop. We\'ll start it for you.');
    console.log('');
    console.log('  [2] Neon (free cloud Postgres — best for Vercel/remote access)');
    console.log('      Sign up at https://neon.tech, create a project, copy the URL.');
    console.log('');
    console.log('  [3] Other Postgres (paste any postgresql:// URL)');
    console.log('');

    const choice = await ask('  Choose [1/2/3]: ');

    if (choice === '1') {
      console.log('\n  Starting Docker Postgres...');
      if (!run('docker', ['compose', 'up', '-d', 'db'])) {
        fail('Docker compose failed. Is Docker Desktop running?');
        console.log('  Install Docker Desktop: https://www.docker.com/products/docker-desktop/');
        process.exit(1);
      }
      env.DATABASE_URL = 'postgresql://dashclaw:dashclaw@localhost:5433/dashclaw';
      ok('Local Postgres running');
    } else if (choice === '2' || choice === '3') {
      const url = await ask('  Paste your PostgreSQL URL: ');
      if (!url || !url.startsWith('postgresql://')) {
        fail('Invalid URL. Must start with postgresql://');
        process.exit(1);
      }
      env.DATABASE_URL = url;
      ok('Database URL saved');
    } else {
      fail('Invalid choice');
      process.exit(1);
    }
  }

  // ── Step 2: Deployment mode ──
  step(2, TOTAL, 'Deployment mode');

  const isRemoteDb = env.DATABASE_URL && !env.DATABASE_URL.includes('localhost') && !env.DATABASE_URL.includes('127.0.0.1');
  let deployUrl = env.NEXTAUTH_URL;

  if (!deployUrl || deployUrl === 'http://localhost:3000') {
    console.log('  How will you access the dashboard?\n');
    console.log('  [1] Local only (http://localhost:3000)');
    console.log('      Run "npm run dev" on this machine.\n');
    console.log('  [2] Cloud (Vercel, Railway, etc.)');
    console.log('      Access from anywhere — phone, laptop, etc.\n');

    const deployChoice = await ask('  Choose [1/2]: ');

    if (deployChoice === '2') {
      const url = await ask('  Your deployment URL (e.g. https://my-dashclaw.vercel.app): ');
      if (url && url.startsWith('http')) {
        deployUrl = url.replace(/\/+$/, '');
      } else {
        warn('Invalid URL — defaulting to localhost. Update NEXTAUTH_URL later.');
        deployUrl = 'http://localhost:3000';
      }
    } else {
      deployUrl = 'http://localhost:3000';
    }
  } else {
    ok(`Dashboard URL: ${deployUrl}`);
  }

  // ── Step 3: Generate secrets ──
  step(3, TOTAL, 'Generating secrets & config');

  if (!env.DASHCLAW_MODE) env.DASHCLAW_MODE = 'self_host';
  if (!env.NEXT_PUBLIC_DASHCLAW_MODE) env.NEXT_PUBLIC_DASHCLAW_MODE = env.DASHCLAW_MODE;
  env.NEXTAUTH_URL = deployUrl;
  if (!env.NEXTAUTH_SECRET) env.NEXTAUTH_SECRET = b64url(32);
  if (!env.DASHCLAW_API_KEY) env.DASHCLAW_API_KEY = `oc_live_${crypto.randomBytes(24).toString('hex')}`;
  if (!env.ENCRYPTION_KEY) env.ENCRYPTION_KEY = b64url(32).slice(0, 32);
  if (!env.CRON_SECRET) env.CRON_SECRET = crypto.randomBytes(32).toString('hex');

  writeEnvFile(env);
  ok('Wrote .env.local');
  console.log(`\n  Your API key: ${redactSecret(env.DASHCLAW_API_KEY)}`);
  console.log(`  Dashboard URL: ${deployUrl}`);

  // ── Step 4: Install dependencies ──
  step(4, TOTAL, 'Installing dependencies');

  const npm = 'npm';
  if (!run(npm, ['install'])) {
    fail('npm install failed. Check your internet connection.');
    process.exit(1);
  }
  ok('Dependencies installed');

  // ── Step 5: Run migrations ──
  step(5, TOTAL, 'Running database migrations');

  const migrations = [
    'scripts/migrate-multi-tenant.mjs',
    'scripts/migrate-cost-analytics.mjs',
    'scripts/migrate-identity-binding.mjs',
    'scripts/migrate-capabilities.mjs',
  ];

  // Set env vars for migration scripts
  const migrationEnv = { ...process.env, ...env };

  function runAsync(cmd, args, opts = {}) {
    return new Promise((resolve) => {
      const child = spawn(cmd, args, { shell: true, stdio: 'pipe', ...opts });
      let stderr = '';
      child.stderr?.on('data', (d) => { stderr += d; });
      child.on('close', (code) => resolve({ code, stderr }));
      child.on('error', () => resolve({ code: 1, stderr: 'spawn error' }));
    });
  }

  const frames = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'];
  let allOk = true;
  for (const script of migrations) {
    const name = script.replace('scripts/', '').replace('.mjs', '');
    const start = Date.now();
    let frame = 0;
    const spinner = setInterval(() => {
      const elapsed = Math.floor((Date.now() - start) / 1000);
      process.stdout.write(`\r  ${frames[frame++ % frames.length]} Running ${name}... (${elapsed}s)`);
    }, 80);
    const result = await runAsync('node', [script], { env: migrationEnv });
    clearInterval(spinner);
    if (result.code === 0) {
      process.stdout.write(`\r  ✅ ${name}${' '.repeat(30)}\n`);
    } else {
      process.stdout.write(`\r  ❌ ${name} — failed${' '.repeat(20)}\n`);
      if (result.stderr) console.log(`     ${result.stderr.trim().split('\n')[0]}`);
      allOk = false;
    }
  }

  if (allOk) {
    ok('All migrations complete');
  } else {
    warn('Some migrations had issues — the dashboard may still work');
  }

  // ── Step 6: Build ──
  step(6, TOTAL, 'Building the dashboard');

  if (!run(npm, ['run', 'build'], { env: migrationEnv })) {
    warn('Build had issues, but npm run dev should still work');
  } else {
    ok('Build complete');
  }

  // ── Done ──
  banner('Setup Complete!');

  const isCloud = deployUrl !== 'http://localhost:3000';

  if (isCloud) {
    console.log('  Your dashboard is configured for cloud deployment.\n');
    console.log('  Next steps:');
    console.log('  1. Push this repo to GitHub (if not already)');
    console.log('  2. Import into Vercel → set these env vars:\n');
    console.log('     DATABASE_URL     = (your Neon connection string)');
    console.log(`     DASHCLAW_MODE    = self_host`);
    console.log(`     NEXT_PUBLIC_DASHCLAW_MODE = self_host`);
    console.log(`     NEXTAUTH_URL     = ${deployUrl}`);
    console.log(`     NEXTAUTH_SECRET  = ${redactSecret(env.NEXTAUTH_SECRET)}`);
    console.log(`     DASHCLAW_API_KEY = ${redactSecret(env.DASHCLAW_API_KEY)}`);
    console.log(`     ENCRYPTION_KEY   = ${redactSecret(env.ENCRYPTION_KEY)}`);
    console.log(`     CRON_SECRET      = ${redactSecret(env.CRON_SECRET)}`);
    console.log('');
    console.log('  3. Set up GitHub OAuth:');
    console.log('     https://github.com/settings/developers → New OAuth App');
    console.log(`     Callback URL: ${deployUrl}/api/auth/callback/github`);
    console.log('     Add GITHUB_ID + GITHUB_SECRET to Vercel env vars');
    console.log('');
    console.log('  4. Deploy and open: ' + deployUrl);
  } else {
    console.log('  Start the dashboard:\n');
    console.log('    npm run dev\n');
    console.log('  Then open: http://localhost:3000');
  }

  console.log('\n  ─────────────────────────────────────────────');
  console.log('  Agent connection snippet (put this on agent machines):\n');
  console.log(`    DASHCLAW_BASE_URL=${deployUrl}`);
  console.log('    DASHCLAW_API_KEY=<value-from-.env.local>');
  console.log('  ─────────────────────────────────────────────\n');
}

main();
